//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.29 at 01:22:13 PM WAT 
//


package de.kisner.xbtjl.model.xml.bittorrent;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://jbtl.sf.net/bittorrent}annouceUrl"/>
 *         &lt;element ref="{http://jbtl.sf.net/bittorrent}hash"/>
 *         &lt;element ref="{http://jbtl.sf.net/bittorrent}file"/>
 *         &lt;element ref="{http://jbtl.sf.net/bittorrent}files"/>
 *         &lt;element ref="{http://jbtl.sf.net/bittorrent}meta"/>
 *         &lt;element ref="{http://jbtl.sf.net/bittorrent}pieces"/>
 *       &lt;/sequence>
 *       &lt;attribute name="totalLength" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "annouceUrl",
    "hash",
    "file",
    "files",
    "meta",
    "pieces"
})
@XmlRootElement(name = "torrent")
public class Torrent
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected AnnouceUrl annouceUrl;
    @XmlElement(required = true)
    protected Hash hash;
    @XmlElement(required = true)
    protected File file;
    @XmlElement(required = true)
    protected Files files;
    @XmlElement(required = true)
    protected Meta meta;
    @XmlElement(required = true)
    protected Pieces pieces;
    @XmlAttribute(name = "totalLength")
    protected Long totalLength;

    /**
     * Gets the value of the annouceUrl property.
     * 
     * @return
     *     possible object is
     *     {@link AnnouceUrl }
     *     
     */
    public AnnouceUrl getAnnouceUrl() {
        return annouceUrl;
    }

    /**
     * Sets the value of the annouceUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnouceUrl }
     *     
     */
    public void setAnnouceUrl(AnnouceUrl value) {
        this.annouceUrl = value;
    }

    public boolean isSetAnnouceUrl() {
        return (this.annouceUrl!= null);
    }

    /**
     * Gets the value of the hash property.
     * 
     * @return
     *     possible object is
     *     {@link Hash }
     *     
     */
    public Hash getHash() {
        return hash;
    }

    /**
     * Sets the value of the hash property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hash }
     *     
     */
    public void setHash(Hash value) {
        this.hash = value;
    }

    public boolean isSetHash() {
        return (this.hash!= null);
    }

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link File }
     *     
     */
    public File getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link File }
     *     
     */
    public void setFile(File value) {
        this.file = value;
    }

    public boolean isSetFile() {
        return (this.file!= null);
    }

    /**
     * Gets the value of the files property.
     * 
     * @return
     *     possible object is
     *     {@link Files }
     *     
     */
    public Files getFiles() {
        return files;
    }

    /**
     * Sets the value of the files property.
     * 
     * @param value
     *     allowed object is
     *     {@link Files }
     *     
     */
    public void setFiles(Files value) {
        this.files = value;
    }

    public boolean isSetFiles() {
        return (this.files!= null);
    }

    /**
     * Gets the value of the meta property.
     * 
     * @return
     *     possible object is
     *     {@link Meta }
     *     
     */
    public Meta getMeta() {
        return meta;
    }

    /**
     * Sets the value of the meta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meta }
     *     
     */
    public void setMeta(Meta value) {
        this.meta = value;
    }

    public boolean isSetMeta() {
        return (this.meta!= null);
    }

    /**
     * Gets the value of the pieces property.
     * 
     * @return
     *     possible object is
     *     {@link Pieces }
     *     
     */
    public Pieces getPieces() {
        return pieces;
    }

    /**
     * Sets the value of the pieces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pieces }
     *     
     */
    public void setPieces(Pieces value) {
        this.pieces = value;
    }

    public boolean isSetPieces() {
        return (this.pieces!= null);
    }

    /**
     * Gets the value of the totalLength property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getTotalLength() {
        return totalLength;
    }

    /**
     * Sets the value of the totalLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTotalLength(long value) {
        this.totalLength = value;
    }

    public boolean isSetTotalLength() {
        return (this.totalLength!= null);
    }

    public void unsetTotalLength() {
        this.totalLength = null;
    }

}
