//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.16 at 08:19:25 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jbtl.sf.net/peer", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.kisner.xbtjl.model.xml.peer;
